/-
Copyright (c) 2024 Alok Singh. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alok Singh
-/
import Mathlib.Order.Filter.Ultrafilter.Basic
import Mathlib.SetTheory.Cardinal.Arithmetic
import Mathlib.Data.Finset.Image

/-!
# Hyperfilter

This file defines the `hyperfilter`, a specific ultrafilter used in nonstandard analysis.
It is constructed to be regular, ensuring saturation properties of the ultrapower.

## Main definitions

* `hyperfilter`: the ultrafilter extending the cofinite filter.
-/

open Set Classical

namespace Filter

variable {α : Type*} [Infinite α]

/-- A bijection between `α` and `Finset α` for infinite `α`.
This exists because `|Finset α| = |α|` for infinite `α`. -/
noncomputable def hyperfilterBijection (α : Type*) [Infinite α] : α ≃ Finset α :=
  Classical.choice (Cardinal.eq.mp (Cardinal.mk_finset_of_infinite α).symm)

/-- The regularizer filter ensuring `|α|`-regularity.
Generated by sets of the form `{x | a ∈ e x}` where `e` is the bijection `α ≃ Finset α`. -/
noncomputable def hyperfilterRegularizer (α : Type*) [Infinite α] : Filter α :=
  Filter.generate {s | ∃ a : α, s = {x | a ∈ hyperfilterBijection α x}}

lemma mem_hyperfilterRegularizer (s : Set α) :
    s ∈ hyperfilterRegularizer α ↔ ∃ S : Finset α, (⋂ a ∈ S, {x | a ∈ hyperfilterBijection α x}) ⊆ s := by
  rw [hyperfilterRegularizer, Filter.mem_generate_iff]
  constructor
  · rintro ⟨S₀, hS₀_sub_g, hS₀_fin, hS₀_inter⟩
    let S' := hS₀_fin.toFinset
    let K := S'.attach.image fun ⟨A, hA⟩ =>
      Classical.choose (hS₀_sub_g ((Set.Finite.mem_toFinset hS₀_fin).mp hA))
    use K
    intro x hx
    apply hS₀_inter
    simp only [Set.mem_sInter]
    intro A hA
    have hA_in_S' : A ∈ S' := (Set.Finite.mem_toFinset hS₀_fin).mpr hA
    let a := Classical.choose (hS₀_sub_g hA)
    have h_eq : A = {y | a ∈ hyperfilterBijection α y} := Classical.choose_spec (hS₀_sub_g hA)
    rw [h_eq]
    simp_rw [Set.mem_iInter] at hx
    refine hx a ?_
    change a ∈ S'.attach.image _
    rw [Finset.mem_image]
    use ⟨A, hA_in_S'⟩
    simp only [Finset.mem_attach, true_and]
    congr
  · rintro ⟨S, hS_sub⟩
    use (S.image (fun a => {x | a ∈ hyperfilterBijection α x}) : Set (Set α))
    refine ⟨?_, ?_, ?_⟩
    · intro A hA
      simp only [Finset.mem_coe, Finset.mem_image] at hA
      obtain ⟨a, _, rfl⟩ := hA
      use a
    · exact (S.image (fun a => {x | a ∈ hyperfilterBijection α x})).finite_toSet
    · simp only [Finset.coe_image, Set.sInter_image]
      exact hS_sub

instance hyperfilter_inf_cofinite_neBot [Infinite α] : (hyperfilterRegularizer α ⊓ cofinite).NeBot := by
  refine Filter.NeBot.mk ?_
  intro h_bot
  rw [← Filter.empty_mem_iff_bot] at h_bot
  rw [Filter.mem_inf_iff] at h_bot
  obtain ⟨u, hu, v, hv, h_inter⟩ := h_bot
  -- u ∈ hyperfilterRegularizer, v ∈ cofinite
  rw [mem_hyperfilterRegularizer] at hu
  obtain ⟨K, hK_sub_u⟩ := hu

  -- Given K, we know {x | K ⊆ e x} is infinite.
  have h_inf : {x | K ⊆ hyperfilterBijection α x}.Infinite := by
    rw [← Set.infinite_image_iff (hyperfilterBijection α).injective.injOn]
    have h_eq_set : (hyperfilterBijection α) '' {x | K ⊆ hyperfilterBijection α x} = {F : Finset α | K ⊆ F} := by
      ext F
      simp only [Set.mem_image, Set.mem_setOf_eq, Equiv.apply_eq_iff_eq_symm_apply]
      constructor
      · rintro ⟨x, hx, h_eq⟩
        rw [h_eq] at hx
        simp only [Equiv.apply_symm_apply] at hx
        exact hx
      · intro hF
        use (hyperfilterBijection α).symm F
        simp [hF]
    rw [h_eq_set]
    change Set.Infinite {F : Finset α | K ⊆ F}
    let f : {a : α // a ∉ K} → Finset α :=
      fun ⟨a, _⟩ => K ∪ {a}
    have hinj : Function.Injective f := by
      intro ⟨a, ha⟩ ⟨b, hb⟩ h
      dsimp [f] at h
      have : a ∈ K ∪ {a} := Finset.mem_union_right _ (Finset.mem_singleton_self _)
      rw [h] at this
      have : a ∈ K ∪ {b} := this
      rw [Finset.mem_union] at this
      cases this with
      | inl hK => contradiction
      | inr hb' =>
        rw [Finset.mem_singleton] at hb'
        rw [Subtype.mk_eq_mk]
        exact hb'
    have h_dom : Infinite {a : α // a ∉ K} := by
      apply Infinite.to_subtype
      change Set.Infinite {a | a ∉ K}
      have : {a | a ∉ K} = Set.univ \ (K : Set α) := by
        ext
        simp only [Set.mem_diff, Set.mem_univ, true_and, Set.mem_setOf_eq, Finset.mem_coe]
      rw [this]
      apply Set.Infinite.diff Set.infinite_univ (Finset.finite_toSet K)
    refine Set.Infinite.mono (s := Set.range f) ?_ ?_
    · rintro _ ⟨⟨a, ha⟩, rfl⟩
      change K ⊆ K ∪ {a}
      apply Finset.subset_union_left
    · rw [← Set.image_univ]
      apply Set.Infinite.image hinj.injOn
      rw [Set.infinite_univ_iff]
      exact h_dom

  -- u ∩ v ⊇ {x | K ⊆ e x} ∩ v
  -- {x | K ⊆ e x} is infinite. v is cofinite.
  -- Intersection is infinite.
  have h_inter_inf : ({x | K ⊆ hyperfilterBijection α x} ∩ v).Infinite := by
    rw [← compl_compl v, ← Set.diff_eq]
    apply Set.Infinite.diff h_inf
    exact hv

  have h_nonempty : ({x | K ⊆ hyperfilterBijection α x} ∩ v).Nonempty := h_inter_inf.nonempty
  have h_sub : {x | K ⊆ hyperfilterBijection α x} ∩ v ⊆ ∅ := by
    have h_eq_inter : (⋂ a ∈ K, {x | a ∈ hyperfilterBijection α x}) = {x | K ⊆ hyperfilterBijection α x} := by
      ext x
      simp only [Set.mem_iInter, Set.mem_setOf_eq, Finset.subset_iff]
    rw [← h_eq_inter]
    refine Set.Subset.trans ?_ h_inter.symm.subset
    apply Set.inter_subset_inter_left
    exact hK_sub_u

  exact h_nonempty.ne_empty (Set.subset_empty_iff.mp h_sub)

/-- The ultrafilter extending the cofinite filter.
We construct it to be `|α|`-regular if `α` is infinite, which ensures `|α|⁺`-saturation of the ultrapower. -/
noncomputable def hyperfilter (α : Type*) [Infinite α] : Ultrafilter α :=
  Ultrafilter.of (hyperfilterRegularizer α ⊓ cofinite)

theorem hyperfilter_le_cofinite : hyperfilter α ≤ @cofinite α :=
  le_trans (Ultrafilter.of_le (hyperfilterRegularizer α ⊓ cofinite)) inf_le_right

theorem _root_.Nat.hyperfilter_le_atTop : (hyperfilter ℕ).toFilter ≤ atTop :=
  hyperfilter_le_cofinite.trans Nat.cofinite_eq_atTop.le

@[simp]
theorem bot_ne_hyperfilter : (⊥ : Filter α) ≠ hyperfilter α :=
  (NeBot.ne inferInstance).symm

theorem notMem_hyperfilter_of_finite {s : Set α} (hf : s.Finite) : s ∉ hyperfilter α := fun hy =>
  absurd (hyperfilter_le_cofinite hf.compl_mem_cofinite) (Ultrafilter.compl_notMem_iff.mpr hy)

@[deprecated (since := "2025-05-24")]
alias nmem_hyperfilter_of_finite := notMem_hyperfilter_of_finite

alias _root_.Set.Finite.notMem_hyperfilter := notMem_hyperfilter_of_finite

@[deprecated (since := "2025-05-24")]
alias _root_.Set.Finite.nmem_hyperfilter := _root_.Set.Finite.notMem_hyperfilter

theorem compl_mem_hyperfilter_of_finite {s : Set α} (hf : Set.Finite s) : sᶜ ∈ hyperfilter α :=
  Ultrafilter.compl_mem_iff_notMem.2 hf.notMem_hyperfilter

alias _root_.Set.Finite.compl_mem_hyperfilter := compl_mem_hyperfilter_of_finite

theorem mem_hyperfilter_of_finite_compl {s : Set α} (hf : Set.Finite sᶜ) : s ∈ hyperfilter α :=
  compl_compl s ▸ hf.compl_mem_hyperfilter

end Filter
