module

public import Mathlib.Order.Filter.Ultrafilter.Basic
public import Mathlib.Order.Filter.Cofinite
public import Mathlib.SetTheory.Cardinal.Arithmetic
public import Mathlib.Data.Finset.Image

/-!
# Nonstandard ultrafilters

This file introduces typeclasses for choosing an ultrafilter to drive
nonstandard extensions, along with a default construction from the cofinite
filter. It also provides regularity data used for saturation results.
-/

@[expose] public section

open Set
open Filter

/-- A chosen ultrafilter on an index type for nonstandard constructions. -/
class NonstandardIndex (ι : Type*) : Type _ where
  /-- The ultrafilter driving the nonstandard extension. -/
  ultrafilter : Ultrafilter ι
  /-- This ultrafilter extends the cofinite filter. -/
  le_cofinite : (ultrafilter : Filter ι) ≤ cofinite

/-- The chosen nonstandard ultrafilter on `ι`. -/
abbrev nonstandardUltrafilter (ι : Type*) [NonstandardIndex ι] : Ultrafilter ι :=
  NonstandardIndex.ultrafilter

@[simp] theorem nonstandardUltrafilter_le_cofinite (ι : Type*) [NonstandardIndex ι] :
    (nonstandardUltrafilter ι : Filter ι) ≤ cofinite :=
  NonstandardIndex.le_cofinite

/-- For `ℕ`, the chosen ultrafilter is eventually atTop. -/
theorem nonstandardUltrafilter_le_atTop [NonstandardIndex ℕ] :
    (nonstandardUltrafilter ℕ : Filter ℕ) ≤ atTop :=
  (nonstandardUltrafilter_le_cofinite (ι := ℕ)).trans_eq Nat.cofinite_eq_atTop

/-- A regularizing family for an ultrafilter, used to derive saturation. -/
class RegularIndex (ι : Type*) [NonstandardIndex ι] : Type _ where
  /-- A family of finite subsets witnessing regularity. -/
  family : ι → Finset ι
  /-- The regularizing family generates sets in the ultrafilter. -/
  family_mem : ∀ a : ι, {i | a ∈ family i} ∈ (nonstandardUltrafilter ι : Filter ι)

/-- A bijection between `ι` and `Finset ι` for infinite `ι`.
This exists because `|Finset ι| = |ι|` for infinite `ι`. -/
noncomputable def regularizingBijection (ι : Type*) [Infinite ι] : ι ≃ Finset ι := by
  classical
  exact Classical.choice (Cardinal.eq.mp (Cardinal.mk_finset_of_infinite ι).symm)

/-- The regularizer filter generated by the regularizing family. -/
noncomputable def regularizingFilter (ι : Type*) [Infinite ι] : Filter ι :=
  Filter.generate {s | ∃ a : ι, s = {x | a ∈ regularizingBijection ι x}}

lemma mem_regularizingFilter (ι : Type*) [Infinite ι] (s : Set ι) :
    s ∈ regularizingFilter ι ↔
      ∃ S : Finset ι,
        (⋂ a ∈ S, {x | a ∈ regularizingBijection ι x}) ⊆ s := by
  classical
  rw [regularizingFilter, Filter.mem_generate_iff]
  constructor
  · rintro ⟨S₀, hS₀_sub_g, hS₀_fin, hS₀_inter⟩
    let S' := hS₀_fin.toFinset
    let K := S'.attach.image fun ⟨A, hA⟩ =>
      Classical.choose (hS₀_sub_g ((Set.Finite.mem_toFinset hS₀_fin).mp hA))
    use K
    intro x hx
    apply hS₀_inter
    simp only [Set.mem_sInter]
    intro A hA
    have hA_in_S' : A ∈ S' := (Set.Finite.mem_toFinset hS₀_fin).mpr hA
    let a := Classical.choose (hS₀_sub_g hA)
    have h_eq : A = {y | a ∈ regularizingBijection ι y} :=
      Classical.choose_spec (hS₀_sub_g hA)
    rw [h_eq]
    simp_rw [Set.mem_iInter] at hx
    refine hx a ?_
    change a ∈ S'.attach.image _
    rw [Finset.mem_image]
    use ⟨A, hA_in_S'⟩
    simp only [Finset.mem_attach, true_and]
    congr
  · rintro ⟨S, hS_sub⟩
    use (S.image (fun a => {x | a ∈ regularizingBijection ι x}) : Set (Set ι))
    refine ⟨?_, ?_, ?_⟩
    · intro A hA
      simp only [Finset.mem_coe, Finset.mem_image] at hA
      obtain ⟨a, _, rfl⟩ := hA
      use a
    · exact (S.image (fun a => {x | a ∈ regularizingBijection ι x})).finite_toSet
    · simp only [Finset.coe_image, Set.sInter_image]
      exact hS_sub

instance regularizingFilter_inf_cofinite_neBot (ι : Type*) [Infinite ι] :
    (regularizingFilter ι ⊓ cofinite).NeBot := by
  classical
  refine Filter.NeBot.mk ?_
  intro h_bot
  rw [← Filter.empty_mem_iff_bot] at h_bot
  rw [Filter.mem_inf_iff] at h_bot
  obtain ⟨u, hu, v, hv, h_inter⟩ := h_bot
  rw [mem_regularizingFilter] at hu
  obtain ⟨K, hK_sub_u⟩ := hu
  have h_inf : {x | K ⊆ regularizingBijection ι x}.Infinite := by
    rw [← Set.infinite_image_iff (regularizingBijection ι).injective.injOn]
    have h_eq_set :
        (regularizingBijection ι) '' {x | K ⊆ regularizingBijection ι x} =
          {F : Finset ι | K ⊆ F} := by
      ext F
      simp only [Set.mem_image, Set.mem_setOf_eq, Equiv.apply_eq_iff_eq_symm_apply]
      constructor
      · rintro ⟨x, hx, h_eq⟩
        rw [h_eq] at hx
        simp only [Equiv.apply_symm_apply] at hx
        exact hx
      · intro hF
        use (regularizingBijection ι).symm F
        simp [hF]
    rw [h_eq_set]
    change Set.Infinite {F : Finset ι | K ⊆ F}
    let f : {a : ι // a ∉ K} → Finset ι :=
      fun ⟨a, _⟩ => K ∪ {a}
    have hinj : Function.Injective f := by
      intro ⟨a, ha⟩ ⟨b, hb⟩ h
      dsimp [f] at h
      have : a ∈ K ∪ {a} := Finset.mem_union_right _ (Finset.mem_singleton_self _)
      rw [h] at this
      have : a ∈ K ∪ {b} := this
      rw [Finset.mem_union] at this
      cases this with
      | inl hK => contradiction
      | inr hb' =>
        rw [Finset.mem_singleton] at hb'
        rw [Subtype.mk_eq_mk]
        exact hb'
    have h_dom : Infinite {a : ι // a ∉ K} := by
      apply Infinite.to_subtype
      change Set.Infinite {a | a ∉ K}
      have : {a | a ∉ K} = Set.univ \ (K : Set ι) := by
        ext
        simp only [Set.mem_diff, Set.mem_univ, true_and, Set.mem_setOf_eq, Finset.mem_coe]
      rw [this]
      apply Set.Infinite.diff Set.infinite_univ (Finset.finite_toSet K)
    refine Set.Infinite.mono (s := Set.range f) ?_ ?_
    · rintro _ ⟨⟨a, ha⟩, rfl⟩
      change K ⊆ K ∪ {a}
      apply Finset.subset_union_left
    · rw [← Set.image_univ]
      apply Set.Infinite.image hinj.injOn
      rw [Set.infinite_univ_iff]
      exact h_dom
  have h_inter_inf : ({x | K ⊆ regularizingBijection ι x} ∩ v).Infinite := by
    rw [← compl_compl v, ← Set.diff_eq]
    apply Set.Infinite.diff h_inf
    exact hv
  have h_nonempty : ({x | K ⊆ regularizingBijection ι x} ∩ v).Nonempty := h_inter_inf.nonempty
  have h_sub : {x | K ⊆ regularizingBijection ι x} ∩ v ⊆ ∅ := by
    have h_eq_inter :
        (⋂ a ∈ K, {x | a ∈ regularizingBijection ι x}) =
          {x | K ⊆ regularizingBijection ι x} := by
      ext x
      simp only [Set.mem_iInter, Set.mem_setOf_eq, Finset.subset_iff]
    rw [← h_eq_inter]
    refine Set.Subset.trans ?_ h_inter.symm.subset
    apply Set.inter_subset_inter_left
    exact hK_sub_u
  exact h_nonempty.ne_empty (Set.subset_empty_iff.mp h_sub)

/-- A default ultrafilter extending the cofinite filter, equipped with regularity data. -/
noncomputable def defaultUltrafilter (ι : Type*) [Infinite ι] : Ultrafilter ι :=
  Ultrafilter.of (regularizingFilter ι ⊓ cofinite)

@[simp] theorem defaultUltrafilter_le_cofinite (ι : Type*) [Infinite ι] :
    (defaultUltrafilter ι : Filter ι) ≤ cofinite :=
  le_trans (Ultrafilter.of_le (regularizingFilter ι ⊓ cofinite)) inf_le_right

/-- Default nonstandard index instance on infinite types.
This instance is low priority so users can override it locally. -/
noncomputable instance (priority := 10) instNonstandardIndex (ι : Type*) [Infinite ι] :
    NonstandardIndex ι :=
  ⟨defaultUltrafilter ι, defaultUltrafilter_le_cofinite ι⟩

-- Regularity data is additional structure on a chosen nonstandard ultrafilter.
-- Users should provide instances appropriate to their chosen ultrafilter.

namespace Filter

variable {α : Type*} [NonstandardIndex α]

@[simp] theorem bot_ne_nonstandardUltrafilter : (⊥ : Filter α) ≠ nonstandardUltrafilter α :=
  (NeBot.ne inferInstance).symm

@[simp] theorem notMem_nonstandardUltrafilter_of_finite {s : Set α} (hf : s.Finite) :
    s ∉ nonstandardUltrafilter α := fun hy =>
  compl_notMem hy <| nonstandardUltrafilter_le_cofinite (ι := α) hf.compl_mem_cofinite

alias _root_.Set.Finite.notMem_nonstandardUltrafilter := notMem_nonstandardUltrafilter_of_finite

@[simp] theorem compl_mem_nonstandardUltrafilter_of_finite {s : Set α} (hf : Set.Finite s) :
    sᶜ ∈ nonstandardUltrafilter α :=
  Ultrafilter.compl_mem_iff_notMem.2 hf.notMem_nonstandardUltrafilter

alias _root_.Set.Finite.compl_mem_nonstandardUltrafilter :=
  compl_mem_nonstandardUltrafilter_of_finite

@[simp] theorem mem_nonstandardUltrafilter_of_finite_compl {s : Set α} (hf : Set.Finite sᶜ) :
    s ∈ nonstandardUltrafilter α :=
  compl_compl s ▸ hf.compl_mem_nonstandardUltrafilter

end Filter
